### ISSUE TITLE
No List (array) returned during token fetching 

### ISSUE THREAD

**Issue by mckinleytabor** [kahiroka/microbot#1]
Was playing around with your code and discovered that on my Microbot Push, the getCharacteristics call on line 119 to UUID 00002a98-0000-1000-8000-00805f9b34fb does not return anything. (So python throws a list index error)

Comparing it to documentation here https://github.com/VRGhost/PyPush/blob/master/docs/microbot_ble_api.md it looks like Characteristic 2A98 in Service 1831 isn't used, but that could just be a limitation of the unofficial documentation.

I can poll the Push and get various Characteristics, so I know I'm connecting and reading data, but I'm somewhat limited in my experience in BLE to understand what I'm looking at. 

This behavior was the same on Push Firmware 0.7.* and upgraded to 1.*. I tried both when the Push was "paired" with the smartphone app, and after a "factory reset" on the devices. (off, on, touch the capacitive button for five seconds until the LE flashes red several times.) 

The platform is a Raspberry Pi running python 3.6.

Thanks for the Code and any insights

**Comment by kahiroka** [comment]
Hi. Thanks for your feedback. It seems to be due to the difference of firmware versions. My MicroBot Push's firmware version is 0.3.11 and probably 2nd gen model. (>= 0.2.0 means 2nd gen. The raw read value from '2A21' is 0x00030b.)
If you use an Android phone you may be able to capture BLE packets on your phone by using 'Enable Bluetooth HCI snoop log' function and analyze the pairing process by using Wireshark.

**Comment by lc2a** [comment]
Hello Kahiroka,

I'm having the same list index error at line 119 to UUID 00002a98-0000-1000-8000-00805f9b34fb.

Sorry, I'm not familiar with BLE, Wireshark Python. Could you help to understand my btsnoop log.
**[btsnoop_hci.log](https://github.com/kahiroka/microbot/files/3093550/btsnoop_hci.log)**

![Capture](https://user-images.githubusercontent.com/1294945/56425238-f4774200-62e5-11e9-9152-62fd001a1c22.JPG)


Thanks in advance. Much appreciated.

**Comment by kahiroka** [comment]
Hi. I updated from 0.3.11 to 1.1.22.2 by using new 'MicroBot' app then caught up with you. I will look into the protocol.
