### ISSUE TITLE
Microbot takes too long to push

### ISSUE THREAD

**Issue by rymsha** [kahiroka/microbot#3]
I'm paying with your code on RPi 3B with the latest Buster installed.

`python3 ./microbot.py xxxx`

writes in console

> use existing token
> Connecting...

after a few seconds 

> connected
> disconnected

with button actually pushed. (So far so good)

After that Microbot quickly blinks with orange signal a few times (probably signaling that "connection is lost")
While keeping things idle Microbot occasionally blinks pink (probably signaling "no connection" ) 

The problem is that "a few seconds" can randomly take from 2 to 30 seconds. Much longer than it would take normally from the phone.

I have an idea that it is due to disconnect and keeping connection would make things more stable. What do you think?

**Comment by scottho7** [comment]
I edited microbot.py, it then seemed more stable.
##########################
    def __initToken(self):
        import time
        if self.newproto:
            s = self.p.getServiceByUUID(MicroBotPush.UUID.SVC1831)
            c = s.getCharacteristics(MicroBotPush.UUID.CHR2A89)[0]
            self.p.writeCharacteristic(c.getHandle()+1, b'\x01\x00')
            time.sleep(1.5)
            id = self.__randomid(16)
            c.write(binascii.a2b_hex(id+"00010040e20100fa01000700000000000000"))
            c.write(binascii.a2b_hex(id+"0fffffffffffffffffffffffffff"+self.__randomid(32)))
        else:
            s = self.p.getServiceByUUID(MicroBotPush.UUID.SVC1831)
            c = s.getCharacteristics(MicroBotPush.UUID.CHR2A98)[0]
            self.p.writeCharacteristic(c.getHandle()+1, b'\x01\x00')
            time.sleep(1.5)
            c.write(binascii.a2b_hex("00000167"+"00"*16))
###########################

**Comment by jenald** [comment]
I am also having this issue. I wanted to retain the connection with the device so I can call push in sequence within 10 seconds gap. So I commented out the disconnect call on microbot.py. However it still disconnects after a few seconds. Does anyone know how to retain bluetooth connection with microbot?

@scottho7 where did you get this commands?
c.write(binascii.a2b_hex(id+"00010040e20100fa01000700000000000000"))
c.write(binascii.a2b_hex(id+"0fffffffffffffffffffffffffff"+self.__randomid(32)))

**Comment by kahiroka** [comment]
Hi @jenald. The disconnection was due to a glitch in token handling.

**Comment by jenald** [comment]
@kahiroka Is there anyway to retain connection?

**Comment by kahiroka** [comment]
@jenald Did you try simple server mode? Maybe you need to update existing token using -u -n options first.
